import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/contexts/NextAuthProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
                  className="h-screen bg-[#272666]  relative overflow-hidden "
                >
                  {/* <div className="absolute inset-0 w-full h-full ">
                    <Image 
                      src="/data/cv.svg" 
                      alt="Auth Background" 
                      fill
                      style={{ objectFit: 'cover' }}
                      priority
                    />
                  </div> */}
                    
                    <div className="bg-[#272666]"
                    >
                     <NextAuthProvider>{children}</NextAuthProvider>
                    </div>
                  </div>
      </body>
    </html>
  );
}
