import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/contexts/NextAuthProvider";
import { SessionProvider } from "next-auth/react"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tickhub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}  >  

         
           <main className='w-full bg-gradient-to-b from-[#0a0a1a] to-[#272666] flex-1'>
            <SessionProvider>
              <NextAuthProvider>{children}</NextAuthProvider>
            </SessionProvider>

            </main>
                      
      </body>
    </html>
  );
}
